apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: "Project for managing applications"
  sourceRepos:
    - https://github.com/my-org/my-repo.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
